sonar.projectKey=safe-zone
sonar.projectName=Safe Zone

sonar.sources=\
backend/api-gateway/src/main/java,\
backend/audit-service/src/main/java,\
backend/eureka/src/main/java,\
backend/media-service/src/main/java,\
backend/product-service/src/main/java,\
backend/user-service/src/main/java,\
frontend/src

sonar.tests=\
backend/api-gateway/src/test/java,\
backend/audit-service/src/test/java,\
backend/eureka/src/test/java,\
backend/media-service/src/test/java,\
backend/product-service/src/test/java,\
backend/user-service/src/test/java

sonar.exclusions=\
**/target/**,\
**/node_modules/**,\
**/dist/**,\
**/*.spec.ts

sonar.java.binaries=\
backend/api-gateway/target/classes,\
backend/audit-service/target/classes,\
backend/eureka/target/classes,\
backend/media-service/target/classes,\
backend/product-service/target/classes,\
backend/user-service/target/classes

sonar.coverage.jacoco.xmlReportPaths=\
backend/api-gateway/target/site/jacoco/jacoco.xml,\
backend/audit-service/target/site/jacoco/jacoco.xml,\
backend/eureka/target/site/jacoco/jacoco.xml,\
backend/media-service/target/site/jacoco/jacoco.xml,\
backend/product-service/target/site/jacoco/jacoco.xml,\
backend/user-service/target/site/jacoco/jacoco.xml

# Exclude in code duplications
sonar.cpd.exclusions=\
backend/**/exception/**,\
backend/**/security/**

# Exclude in code coverage
sonar.coverage.exclusions=\
backend/**/exception/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8