services:
  jenkins:
    build: .
    container_name: jenkins

    ports:
      - "9090:8080"
      - "50000:50000"

    environment:
      JENKINS_ADMIN_PASSWORD: ${JENKINS_ADMIN_PASSWORD}
      JENKINS_URL: ${JENKINS_URL}

      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

      GITHUB_USERNAME: ${GITHUB_USERNAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

      JWT_SECRET: ${JWT_SECRET}
      GATEWAY_KEYSTORE_PASSWORD: ${GATEWAY_KEYSTORE_PASSWORD}

      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    volumes:
      - jenkins_home:/var/jenkins_home

    networks:
      - ci-network
volumes:
  jenkins_home:

networks:
  ci-network:
    external: true
